### ISSUE TITLE
Code linting

### ISSUE THREAD

**Issue by saracalihan** [axe-api/axe-api#149]
We do not have any standards for naming, flow, or similar operations to increase the quality and readability of the code.

The contributing document should be written then rule checkers must be added.

**Comment by saracalihan** [comment]
We can use [eslint](https://eslint.org/) for linter, for faster development we can use [prattier](https://prettier.io/) or eslint plugin to check lint while typing and [husky](https://typicode.github.io/husky/#/) for commit message checker.

I think those patterns should be used for nomenclature:
* **Component**, **View** and **Class**: `PascalCase`
* **Variables**: `camelCase`
* **Urls**, **events**(ws): `kebab-case`
* **Environment variables**, **constants**: `MACRO_CASE`
* **Database table** and **field names**: `snake_case`

I suggest [this](https://github.com/acikkaynak/deprem-yardim-frontend/blob/development/CONTRIBUTING.md#commit-messages) styles for commit messages.

@ozziest @burakack  What do you thing about that?

**Comment by ozziest** [comment]
I agree we should have standards. But we don't need to write documentation about it. Eslint is already configured in the root folder. The thing we should do is add Eslint checks to the CI/CD pipelines.

But I disagree with commit styling. Because I don't understand the benefits.

I suggest splitting the issue to;
  - Eslint checks (GitHub Actions)
  - Prettier configurations (maybe checks in actions)
  - Commit message styles.
