### ISSUE TITLE
http module support

### ISSUE THREAD

**Issue by ozziest** [axe-api/axe-api#47]
## Motivation

Currently, we are using Express as the request handler. But we can use different frameworks such as Fastify.

## Implementation 

- It should be configurable.
- `express` packages are installed to the `axe-api`. We should remove them from the `axe-api`. In `axe-api-template` we should install `express` as the default framework. Developers must install `fastify` dependencies if they want to use it. (I am not sure we can do it.)
- Almost in everywhere we use `app: Express` keywords. We should create an `IFramework` interface. Also, we should have `FastifyFramework` and `ExpressFramework` that implement `IFramework`. By configuration, we should create an instance of any of them. But the developers always should use `IFramework`.
- We should create our `IRequest`, `IResponse` interfaces. They should be framework agnostic. 
- Many unit and integration tests should be changed.
- We are extending the Express namespace for `currentLanguage` at some point. We should be able to do it dynamically by the configuration.

**Comment by saracalihan** [comment]
We can change our code to abstract the server related codes and use the framework selected in the configuration file.

Currently, i prefer fastify to express.js because it's faster. Express is more easy to use but its not a big deal for me also two framework has express like usage and fastify can provide object typed routes .

I think we can enable this frameworks at this stage:
+ [Express.js](https://expressjs.com/) (**_already implemented_**)
+ [Fastify](https://www.fastify.io/) (**_must be implemented_**)
+ [Koa.js](https://koajs.com/)
+ [Hapi.js](https://koajs.com/)

After deciding on the main structure, if it is suitable for you, I can start developing on this subject.

**Comment by ozziest** [comment]
Looks great. We can start with `Fastify`. But before jumping in. give me some time to work on it what kind of parts will be changed in the core structure.  I will create a detailed roadmap.

**Comment by ozziest** [comment]
@saracalihan , I updated the issue content. I think we can start to dig and see what happens.

**Comment by saracalihan** [comment]
> @saracalihan , I updated the issue content. I think we can start to dig and see what happens.

Ok, i'm starting to develop

**Comment by ozziest** [comment]
I reviewed the PR and I think it is more complicated than we though. I suggest that we should remove this feature from `v0.30.0` and work on more deeply, and check Nest.js examples.

**Comment by ozziest** [comment]
I discovered Axe API can use the [http](https://nodejs.org/api/http.html) module directly. We do not need to use Express.js or Fastify. 

Using any other frameworks creates a strong bond with those frameworks.
